### ISSUE TITLE
Cleanup of unneeded dependencies

### ISSUE THREAD

**Issue by Edke** [singer-io/tap-pipedrive#10]
Just looking though the code, found out one early requirement, `click` is fantastic replacement for argparse and initially wanted to build argument parsing using click but then replaced with already implemented argparse from singer lib

https://github.com/singer-io/tap-pipedrive/blob/ac2da32df561f71d1fabae0365f27aaad8c24642/setup.py#L16

Should I remove it ?

**Comment by cmerrick** [comment]
yes, please remove unused dependencies
