### ISSUE TITLE
Occasionally got error code 520 

### ISSUE THREAD

**Issue by Hoanglinh1201** [singer-io/tap-pipedrive#109]
Our stitch pipedrive randomly got this error one every few runs. 

`2022-03-10 06:13:41,880Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=1.0308310985565186, tags={'status': 'failed', 'endpoint': 'deal_products'})
2022-03-10 06:13:41,880Z    tap - CRITICAL HTTP-error-code: 520, Error: Unknown Error`

Not so sure how to fix this issue. Does anyone come across this error and fortunately have the solution?

**Comment by danpermun** [comment]
Hi,

I had the same issue for two days and suddenly it stopped without any changes made.

Im my case, the destination is an AWS Redshift cluster, but I don´t know if the problem occurs between pipedrive and stitch stage infra or between stitch infra and Redshift cluster.

**Comment by Gabrieldlramos** [comment]
I ran into the same mistake, but it took a little bit more time to solve it, is there anyone still getting this error?

**Comment by Hoanglinh1201** [comment]
For some reasons the error is no longer there. I close the issue for now. Thanks everyone involved.
