### ISSUE TITLE
Loads stopped since March 6th

### ISSUE THREAD

**Issue by tponkane** [singer-io/tap-pipedrive#132]
Hi everyone,

We've noticed that in Stitch, loads have virtually stopped since March 6th, 2023. Extractions seem to run for 24 hours, logs seem to consist nearly 100% of

`2023-03-23 08:59:56,767Z    tap - INFO HTTP request to "deal_products" endpoint took 0.386s, returned status code 200`
`2023-03-23 08:59:56,768Z    tap - INFO replicated 0 records from "deal_products" endpoint` 

Anyone else experiencing the same or know a workaround? Many thanks in advance!

<img width="790" alt="img" src="https://user-images.githubusercontent.com/123646089/227493985-793c9390-54b7-4b8f-b43c-0702740821c8.png">

<img width="582" alt="img2" src="https://user-images.githubusercontent.com/123646089/227495255-220fd8dd-d917-4144-8531-2b7c708d0c6a.png">

**Comment by GeorgeTouros** [comment]
Same problem here. It's the dealflow object that has been causing the trouble. We have managed to continue the data syncs, but we have omitted the problematic object. This is causing us problems but at least we have some data. 
Did you manage to find a solution?

**Comment by opalh** [comment]
Same issue here, do we have any update on a solution?

**Comment by dsprayberry** [comment]
Please contact Stitch support for assistance on this front
