### ISSUE TITLE
Singer API error

### ISSUE THREAD

**Issue by SeanFLynch** [singer-io/tap-pipedrive#14]
Hi,

We keep getting this error message with the Pipedrive Tap:

"2018-03-02 10:39:31,903Z   main - INFO Exit status is: Tap failed with code 1 and error message: "Errors during transform". Target succeeded."

Any ideas on this?

Sean.

**Comment by KAllan357** [comment]
Hi @SeanFLynch, I looked you up in our system - usually the logs in the Stitch UI will reveal a bit more context. Here's what I found:

```
2018-03-02 10:39:31,697Z    tap - CRITICAL Errors during transform
2018-03-02 10:39:31,697Z    tap - 	last_login: 0000-00-00 00:00:00 does not match {'type': ['string', 'null'], 'format': 'date-time'}
```

We're using some Python code to transform the value Pipedrive is returning into a datetime object. In this case, its failing to parse a string `"0000-00-00 00:00:00"` into a datetime.

The easiest path forward would be to modify the offending row in Pipedrive or to deselect that `last_login` column in Stitch.

**Comment by KAllan357** [comment]
@SeanFLynch any update here?

**Comment by chase2963** [comment]
I'm getting the same error as well. It seems to happen when you have a user you've invited to the pipedrive but they haven't signed in yet

**Comment by chase2963** [comment]
I think it has to do with a user that you have like this: 

![image 2018-03-16 at 2 32 11 pm](https://user-images.githubusercontent.com/9396468/37543368-ee8be386-2926-11e8-8c3b-6b97135ae342.png)

**Comment by chase2963** [comment]
that error went away when I removed that user that hadn't logged in

**Comment by KAllan357** [comment]
Sounds good! :+1:
