### ISSUE TITLE
Errors during Transform for `Products`

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-pipedrive#16]
2018-03-16 22:11:25,388Z    tap - Errors during transform: [prices.USD.overhead_cost: None does not match {'type': 'number'},

**Comment by honkycat** [comment]
I'm also seeing this error, it is blocking me from using the integration for stitch.

**Comment by ajmers** [comment]
@dylan-stitch @honkycat Here's a PR to fix this issue: https://github.com/singer-io/tap-pipedrive/pull/26
