### ISSUE TITLE
WARNING Removed email.0.label during transforms

### ISSUE THREAD

**Issue by Edke** [singer-io/tap-pipedrive#2]
When I run against the test pipedrive account today, I see this warning:

```
WARNING Removed 2 paths during transforms:
	email.0.label
	phone.0.label
```

**Comment by Edke** [comment]
@cmerrick This means that this structure exists in payload but is not included in schema, therefore was removed.

These warnings generally mean schema and payload are not synced. To solve this properly, we need:

which endpoint / stream
complete payload
According to this we can then update schema for that stream and re-test.

**Comment by cmerrick** [comment]
This came from the test account that you have access to, you can reproduce by running tap-pipedrive without any initial state.

**Comment by Edke** [comment]
Yes, I can see that now, but what changed ? As last time I was working with that data (Friday I guess) it worked without any Warnings. 

So new / changed data or API changed ?

**Comment by Edke** [comment]
Fixed all schema issues against current test account. To work, also PR https://github.com/singer-io/tap-pipedrive/pull/6 needs to be merged.

**Comment by cmerrick** [comment]
I think there was new or changed data
