### ISSUE TITLE
Deal_Products table isn't being replicated in Stitch

### ISSUE THREAD

**Issue by HWdata** [singer-io/tap-pipedrive#28]
Hello,
We need the Deal_Product table in our BI tool and it's not currently replicated in Stitch. Do you know when this table will be replicated?
Thanks!

**Comment by briansloane** [comment]
This sounds like an interesting feature request. Can you provide more detail around deal products and what you would expect to see? Do you know the best way to get this from the Pipedrive API?

**Comment by HWdata** [comment]
Here's the relevant docs:
https://developers.pipedrive.com/docs/api/v1/?#!/Deals/put_deals_id_products_deal_product_id

**Comment by briansloane** [comment]
Thank you for this, @HWdata. This information will be helpful when adding this feature. I don't have a timeline for any work on this. We'll update here when our team picks up any work related to this. In the meantime, we would welcome a PR for review to expedite the process.

**Comment by HWdata** [comment]
What is a PR?

**Comment by briansloane** [comment]
A PR is a [Pull Request on GitHub](https://help.github.com/articles/about-pull-requests/). They are used for managing contributions to developers on projects. When somebody from the open source community implements this feature, they can create a PR and the Singer team will review the code for inclusion.

**Comment by bdemontecler** [comment]
Hello, i just made 4 pull request for this issue  #32  #33 #34  #35 , can you say me if i did it right ? I'm not a pro developer :)

**Comment by ty-dev** [comment]
Any plans to complete deal_products request now that #36 has been completed?

**Comment by dmosorast** [comment]
Hi @ty-dev, looking at this more closely, it seems that I closed this issue in error. I haven't heard more about DealsProducts, but with the `PipeDriveIterStream` base class, this should be doable. It'd work much like the [DealFlow](https://github.com/cross-entropy/tap-pipedrive/blob/master/tap_pipedrive/streams/dealflow.py) stream. Feel free to submit a PR if you can get it up and running locally and test that theory.
