### ISSUE TITLE
Take out the newly added "dealflow" table 

### ISSUE THREAD

**Issue by Forestk11** [singer-io/tap-pipedrive#39]
Hi there, 

I currently use stitch to sync pipedrive data to my database. Same issue as another thread - the "dealflow" table was added a few days back and means a massive amount of data is being sync (from 14k rows a day to 500k rows a day) - and this has eaten up all my row limit. 

Is there a way to stop syncing the "dealflow" table please? 

Any help on this would be much appreciated !

**Comment by dmosorast** [comment]
Closing this to keep conversation in the existing issue, #37
