### ISSUE TITLE
`dealflow` stream only captures `deal`s that have changed stages rather than all possible update paths

### ISSUE THREAD

**Issue by renandiasCobli** [singer-io/tap-pipedrive#40]
#42 is being worked on to address this issue. See [this comment](https://github.com/singer-io/tap-pipedrive/issues/40#issuecomment-438006906) for the current state of this thread.

------------------------------------

A simple way to replicate this issue:

Get all deals id in table "deals" and check those that are not in item_id "dealflow" table.

Since every deal exists, all of them should be on dealflow with a field_key of "add_time", but this is not happening.
The difference is not only the deleted deals.

Sorry, I have 0 hypothesis for this behavior.

Obs: I am using this library with stitchdata

**Comment by alewis-ce** [comment]
I have also seen this issue and am working on a PR to address it. 
The primary issue is that the stream looks for a stage_change_time for a deal, which misses deals that have been added but that have not changed stages.

**Comment by timvisher** [comment]
Thanks for the submitting the issue and thanks for confirming it @alewis-ce!

Should we expect your PR at some point in the nearish future?

@alewis-ce Can you confirm that my title change here is appropriate?

**Comment by timvisher** [comment]
@alewis-ce Ping. :)

If your PR addresses this issue can you add `Fixes https://github.com/singer-io/tap-pipedrive/issues/40` to it so this Issue will automatically close when we merge it?

**Comment by alewis-ce** [comment]
@timvisher I believe my PR should fix this issue, as long as I understood it correctly the first time. The PR will fix the problem that the stream is not currently getting all deals when they are first added if they haven't changed stages.

The stream is designed to catch the flow of deals through the funnel and should therefore catch all deal additions and stage changes. It is **not** designed to catch any other changes to a deal (value, close date, owner, etc). 

@renandiasCobli Are you expecting the dealflow stream to get these additional changes, or are you just looking for deal additions and stage changes?
