### ISSUE TITLE
Not all selected tables are being replicated

### ISSUE THREAD

**Issue by chandrasen-rajashekar** [singer-io/tap-pipedrive#62]
I am using Stitchdata to replicate pipedrive data. I have selected the tables **activities,  activity_types, deal_products, dealflow, deals, files, filters, organisations, persons, pipeline, products, stages and users** to replicate. I have noticed that, since 19th of September only the tables **dealflow and deal_products** are being replicated and none of the other tables are being replicated. Can someone please help me fix this issue? Any information which helps me fix the issue is highly appreciated. Thanks in advance.

**Latest extraction log from Stitchdata:**
[latest_extraction_logs.pdf](https://github.com/singer-io/tap-pipedrive/files/3648285/latest_extraction_logs.pdf)

**Latest error email that I received from Stitch:**
<img width="995" alt="Screenshot 2019-09-24 at 18 32 35" src="https://user-images.githubusercontent.com/53179903/65531227-bbc53f80-def9-11e9-9672-17fa7bc85dbb.png">

**Comment by dmosorast** [comment]
@chandrasen-rajashekar This sounds like an error that was fixed as of this afternoon (EST), closing for now. Please reopen if you're still not seeing data.

**Comment by chandrasen-rajashekar** [comment]
@dmosorast it did solve my issue. Thanks a lot for fixing the error it did ease my life a lot.
