### ISSUE TITLE
Proper handling of API HTTP request exceptions

### ISSUE THREAD

**Issue by Edke** [singer-io/tap-pipedrive#7]
Issues:
- [x] https://github.com/singer-io/tap-pipedrive/pull/1#discussion_r143616170
- [x] https://github.com/singer-io/tap-pipedrive/pull/1#discussion_r143616343
- [x] https://github.com/singer-io/tap-pipedrive/pull/1#discussion_r143616418

**Comment by Edke** [comment]
@cmerrick so tap should a) raise exception or b) use logger.error() and exit(1) ?

**Comment by Edke** [comment]
@cmerrick and about which exceptions:

1. any exception that failed to retrieve payload means tap is tails, needs to be stopped and re-run,
2. no matter if timeout, connectionerror or response error (500, 400, ...), always terminate tap

right ?

**Comment by cmerrick** [comment]
Any unrecoverable exception should be allowed to raise to the top-level.  exit(1) should never be called.  Please follow a pattern like this to log exceptions that reach the top level as critical and then re-raise: https://github.com/singer-io/tap-hubspot/pull/48/files
